import { test, expect, expectCanvasPainted } from '../support/mock-api'

test('keeps project and graph controls usable on mobile', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'mobile', 'mobile-only layout assertion')
  await page.goto('/')
  await page.getByRole('button', { name: 'Create project' }).click()
  await page.getByLabel('Project name').fill('Mobile model')
  await page.getByRole('button', { name: 'Create project' }).last().click()
  await page.getByRole('button', { name: 'Add node' }).last().click()
  await page.getByLabel('Title').fill('Customer trust')
  await page.getByText('outcome', { exact: true }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: 'Add node' }).last().click()

  await expect(page.getByLabel('Project', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Search graph')).toBeVisible()
  await expect(page.getByTestId('graph-surface')).toBeVisible()
  await expectCanvasPainted(page)
  await page.getByRole('button', { name: /Customer trust/ }).click()
  await page.getByRole('button', { name: 'Estimate', exact: true }).click()
  const editor = page.getByLabel('Squiggle editor and distribution viewer')
  await expect(editor).toBeVisible()
  await expect(editor.getByTestId('squiggle-editor')).toBeVisible()
  const editorBox = await editor.boundingBox()
  expect(editorBox).not.toBeNull()
  expect(editorBox!.x).toBeGreaterThanOrEqual(0)
  expect(editorBox!.x + editorBox!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  await page.screenshot({ path: 'artifacts/workbench-mobile.png', fullPage: true })
})
