import { expect, test } from '@playwright/test'

test('creates and reads a typed model through the real Axum API', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Create your first project' })).toBeVisible()

  await page.getByRole('button', { name: 'Create project' }).click()
  await page.getByLabel('Project name').fill('Real API model')
  await page.getByRole('button', { name: 'Create project' }).last().click()
  await expect(page.getByRole('heading', { name: 'Start with a system element' })).toBeVisible()

  await page.getByRole('button', { name: 'Add node' }).last().click()
  await page.getByLabel('Title').fill('Fast feedback')
  await page.getByRole('button', { name: 'Add node' }).last().click()

  await page.getByRole('button', { name: 'Add node' }).first().click()
  await page.getByLabel('Title').fill('Learning rate')
  await page.getByRole('button', { name: 'Add node' }).last().click()

  await page.getByRole('button', { name: 'Relationship', exact: true }).click()
  await page.getByRole('form', { name: 'Add relationship' }).getByRole('combobox').first().selectOption('part_of')
  await page.getByLabel('Source').selectOption('A')
  await page.getByLabel('Destination').selectOption('B')
  await page.getByRole('button', { name: 'Add relationship' }).click()

  await expect(page.getByTestId('graph-surface')).toBeVisible()
  await expect(page.getByText('1 relationships')).toBeVisible()
  await page.getByRole('button', { name: /Fast feedback/ }).click()
  await expect(page.getByRole('heading', { name: 'Fast feedback' })).toBeVisible()
  await expect(page.getByText('part of', { exact: true })).toBeVisible()
  await expect(page.getByText('A', { exact: true }).last()).toBeVisible()
  await expect(page.getByText('B', { exact: true }).last()).toBeVisible()
  await expect(page.getByText('r3')).toBeVisible()

  await page.getByRole('button', { name: 'Edit part of relationship A to B' }).click()
  await page.getByLabel('Description').fill('Learning is part of feedback.')
  await page.getByLabel('Metadata').fill('{"source":"ADR-2"}')
  await page.getByRole('button', { name: 'Save relationship' }).click()
  await expect(page.getByText('r4')).toBeVisible()

  await page.getByRole('button', { name: 'Edit part of relationship A to B' }).click()
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm delete' }).click()
  await expect(page.getByText('0 relationships')).toBeVisible()

  await page.getByRole('button', { name: 'Relationship', exact: true }).click()
  await page.getByRole('form', { name: 'Add relationship' }).getByRole('combobox').first().selectOption('part_of')
  await page.getByLabel('Source').selectOption('A')
  await page.getByLabel('Destination').selectOption('B')
  await page.getByRole('button', { name: 'Add relationship' }).click()
  await expect(page.getByText('1 relationships')).toBeVisible()

  await page.getByRole('button', { name: 'Details' }).click()
  await page.getByLabel('Title').fill('Rapid feedback')
  await page.getByLabel('Description').fill('Short feedback loops.')
  await page.getByLabel('Metadata').fill('{"owner":"platform"}')
  await page.getByRole('button', { name: 'Save details' }).click()
  await expect(page.getByRole('heading', { name: 'Rapid feedback' })).toBeVisible()
  await expect(page.getByText('Short feedback loops.')).toBeVisible()
  await expect(page.getByText(/"owner": "platform"/)).toBeVisible()

  await page.getByRole('button', { name: 'Add evidence' }).click()
  await page.getByLabel('Summary').fill('Queueing observed during review')
  await page.getByLabel('Source').fill('Delivery dashboard')
  await page.getByRole('form', { name: 'Add evidence' }).getByRole('button', { name: 'Add evidence' }).click()
  await expect(page.getByText('Queueing observed during review')).toBeVisible()
  await expect(page.getByText(/Delivery dashboard · r0/)).toBeVisible()
  await page.getByRole('button', { name: /Edit evidence/ }).click()
  await page.getByLabel('Summary').fill('Queueing confirmed during review')
  await page.getByRole('button', { name: 'Save evidence' }).click()
  await expect(page.getByText('Queueing confirmed during review')).toBeVisible()
  await expect(page.getByText(/Delivery dashboard · r1/)).toBeVisible()
  await page.getByRole('button', { name: /Edit evidence/ }).click()
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm delete' }).click()
  await expect(page.getByText('No qualitative evidence recorded.')).toBeVisible()

  await page.getByRole('button', { name: 'Estimate' }).click()
  await page.getByLabel('Value on [0, 1]').fill('0.65')
  await page.getByLabel('Provenance').fill('Weekly review')
  await page.getByRole('button', { name: 'Set estimate' }).click()
  await expect(page.getByText('Point · 0.65')).toBeVisible()
  await expect(page.getByText('Weekly review')).toBeVisible()

  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export project' }).click()
  const download = await downloadPromise
  const archivePath = await download.path()
  expect(download.suggestedFilename()).toMatch(/\.optimist\.json$/)
  expect(archivePath).not.toBeNull()

  await page.getByRole('button', { name: 'Add node' }).first().click()
  await page.getByLabel('Title').fill('Temporary factor')
  await page.getByRole('button', { name: 'Add node' }).last().click()
  await expect(page.getByText('3 nodes')).toBeVisible()

  await page.getByRole('button', { name: 'Import project' }).click()
  await page.locator('input[type="file"]').setInputFiles(archivePath!)
  await expect(page.getByText('2', { exact: true }).first()).toBeVisible()
  await page.getByLabel('Type A to confirm').fill('A')
  await page.getByRole('button', { name: 'Replace project' }).click()

  await expect(page.getByText('2 nodes')).toBeVisible()
  await expect(page.getByText('1 relationships')).toBeVisible()
  await expect(page.getByRole('button', { name: /Temporary factor/ })).toHaveCount(0)
  await page.getByRole('button', { name: /Rapid feedback/ }).click()
  await expect(page.getByText('Point · 0.65')).toBeVisible()
  await expect(page.getByText('Weekly review')).toBeVisible()
  await expect(page.getByText(/"owner": "platform"/)).toBeVisible()

  await page.getByRole('button', { name: 'Add node' }).first().click()
  await page.getByLabel('metric').check()
  await page.getByLabel('Title').fill('Cycle time')
  await page.getByLabel('Unit').fill('days')
  await page.getByRole('button', { name: 'Add node' }).last().click()

  for (const title of ['Automate review', 'Pair review']) {
    await page.getByRole('button', { name: 'Add node' }).first().click()
    await page.getByLabel('intervention').check()
    await page.getByLabel('Title').fill(title)
    await page.getByRole('button', { name: 'Add node' }).last().click()
  }

  await page.getByRole('button', { name: 'Relationship', exact: true }).click()
  await page.getByRole('form', { name: 'Add relationship' }).getByRole('combobox').first().selectOption('contributes')
  await page.getByLabel('Source').selectOption('A')
  await page.getByLabel('Destination').selectOption('B')
  await page.getByLabel('Signed effect on [-1, 1]').fill('0.7')
  await page.getByLabel('Mechanism').fill('Short loops increase learning.')
  await page.getByRole('button', { name: 'Add relationship' }).click()

  await page.getByRole('button', { name: 'Relationship', exact: true }).click()
  await page.getByRole('form', { name: 'Add relationship' }).getByRole('combobox').first().selectOption('measures')
  await page.getByLabel('Source').selectOption('C')
  await page.getByLabel('Destination').selectOption('A')
  await page.getByLabel('Measurement polarity').selectOption('lower_is_better')
  await page.getByRole('button', { name: 'Add relationship' }).click()

  await page.getByRole('button', { name: /Cycle time/ }).click()
  await page.getByRole('button', { name: 'Add observation for A' }).click()
  await page.getByLabel('Value').fill('4.2')
  await expect(page.getByLabel('Unit')).toHaveValue('days')
  await page.getByLabel('Source').fill('Delivery dashboard')
  await page.getByLabel('Include known measurement error').check()
  await page.getByLabel('Standard deviation').fill('0.2')
  await page.getByRole('button', { name: 'Add observation', exact: true }).click()
  await expect(page.getByText('4.2 days')).toBeVisible()
  await expect(page.getByText(/Delivery dashboard · σ 0.2/)).toBeVisible()
  await page.getByRole('button', { name: 'Correct observation 0 for A' }).click()
  await page.getByLabel('Corrected value').fill('3.9')
  await expect(page.getByText('Delivery dashboard', { exact: true })).toBeVisible()
  await expect(page.getByText('0.2', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Append correction' }).click()
  await expect(page.getByText('3.9 days')).toBeVisible()
  await expect(page.getByText('Superseded by #1')).toBeVisible()
  await expect(page.getByText('Correction of #0')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Correct observation 0 for A' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Correct observation 1 for A' })).toBeVisible()

  await page.getByRole('button', { name: 'Relationship', exact: true }).click()
  await page.getByRole('form', { name: 'Add relationship' }).getByRole('combobox').first().selectOption('synergizes_with')
  await page.getByLabel('Source').selectOption('D')
  await page.getByLabel('Destination').selectOption('E')
  await page.getByRole('button', { name: 'Add relationship' }).click()
  await expect(page.getByText('5 nodes')).toBeVisible()
  await expect(page.getByText('4 relationships')).toBeVisible()

  await page.getByRole('button', { name: /Automate review/ }).click()
  await page.getByRole('button', { name: 'Edit duration estimate' }).click()
  await page.getByLabel('Distribution').selectOption('log_normal')
  await page.getByLabel('Log location').fill('2')
  await page.getByLabel('Log scale').fill('0.3')
  await page.getByLabel('Provenance').fill('Planning workshop')
  await page.getByRole('button', { name: 'Set estimate' }).click()
  await expect(page.getByText('LogNormal · μ 2, σ 0.3')).toBeVisible()

  await page.getByRole('button', { name: 'Edit success probability estimate' }).click()
  await page.getByLabel('Distribution').selectOption('beta')
  await page.getByLabel('Alpha').fill('8')
  await page.getByRole('spinbutton', { name: 'Beta', exact: true }).fill('2')
  await page.getByRole('button', { name: 'Set estimate' }).click()
  await expect(page.getByText('Beta · α 8, β 2')).toBeVisible()

  await page.getByRole('button', { name: 'Add cost dimension' }).click()
  await page.getByRole('textbox', { name: 'Dimension', exact: true }).fill('engineer_days')
  await page.getByLabel('Value').fill('12')
  await page.getByRole('button', { name: 'Set estimate' }).click()
  await expect(page.getByText('engineer_days', { exact: true })).toBeVisible()
  await expect(page.getByText('Point · 12')).toBeVisible()

  await page.getByRole('button', { name: 'Edit engineer_days cost estimate' }).click()
  await page.getByLabel('Value').fill('10')
  await page.getByRole('button', { name: 'Replace estimate' }).click()
  await expect(page.getByText('Point · 10')).toBeVisible()
  await page.getByRole('button', { name: 'Edit engineer_days cost estimate' }).click()
  await page.getByRole('button', { name: 'Remove', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm remove' }).click()
  await expect(page.getByText('No cost dimensions configured.')).toBeVisible()

  await page.getByRole('button', { name: 'Edit synergizes with relationship D to E' }).click()
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm delete' }).click()
  await expect(page.getByText('3 relationships')).toBeVisible()
  await page.getByRole('button', { name: 'Delete node' }).click()
  await page.getByRole('button', { name: 'Confirm delete D' }).click()
  await expect(page.getByText('4 nodes')).toBeVisible()
  await expect(page.getByRole('button', { name: /Automate review/ })).toHaveCount(0)
})
