import { expect, test } from '@playwright/test'
import { addNode, createProject } from '../support/workbench'

test('sets, replaces, and removes intervention estimates', async ({ page }) => {
  await createProject(page, 'Intervention estimates')
  await addNode(page, 'Automate review', 'intervention')
  await page.getByRole('button', { name: /Automate review/ }).click()
  await page.getByRole('button', { name: 'Edit duration estimate' }).click()
  await page.getByLabel('Squiggle source').fill('lognormal(2, 0.3)')
  await expect(page.getByText(/Lognormal ·/)).toBeVisible()
  await page.getByRole('button', { name: 'Replace estimate' }).click()
  await expect(page.locator('.estimate-row').first().getByText(/Empirical/)).toBeVisible()

  await page.getByRole('button', { name: 'Add cost dimension' }).click()
  await page.getByRole('textbox', { name: 'Dimension', exact: true }).fill('engineer_days')
  await page.getByLabel('Squiggle source').fill('pointMass(12)')
  await expect(page.getByText(/effective samples/)).toBeVisible()
  await page.getByRole('button', { name: 'Set estimate' }).click()
  await page.getByRole('button', { name: 'Edit engineer_days cost estimate' }).click()
  await page.getByLabel('Squiggle source').fill('pointMass(10)')
  await expect(page.getByText(/effective samples/)).toBeVisible()
  await page.getByRole('button', { name: 'Replace estimate' }).click()
  const cost = page.locator('.estimate-row').filter({ hasText: 'engineer_days' })
  await expect(cost.getByText('Empirical · 2,048 samples')).toBeVisible()
  await expect(cost.getByText(/Squiggle · pointMass\(10\)/)).toBeVisible()
  await page.getByRole('button', { name: 'Edit engineer_days cost estimate' }).click()
  await page.getByRole('button', { name: 'Remove', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm remove' }).click()
  await expect(page.getByText('No cost dimensions configured.')).toBeVisible()
})
