import { expect, test } from '@playwright/test'
import { createProject } from '../support/workbench'

test('defines and derives a metric estimate in native units', async ({ page }) => {
  await createProject(page, 'Native metric quantity')
  await page.getByRole('button', { name: 'Add node' }).last().click()
  const dialog = page.locator('.node-dialog')
  await dialog.getByLabel('metric').check()
  await dialog.getByLabel('Title').fill('Lead time')
  await dialog.getByLabel('Unit').fill('days')
  await dialog.getByRole('button', { name: 'Continue' }).click()

  await dialog.getByLabel('Aggregation').fill('p95 weekly')
  await dialog.getByLabel('Support').selectOption('bounded')
  await dialog.getByLabel('Minimum').fill('0')
  await dialog.getByLabel('Maximum').fill('30')
  await dialog.getByLabel('Operational definition').fill('Elapsed calendar days from commit to production for completed changes.')
  await dialog.getByLabel('Reference time').fill('Next 30 days')
  await dialog.getByLabel('Resolution source').fill('Delivery dashboard')
  await dialog.getByLabel('Add a current estimate').check()
  await dialog.getByLabel('Value in days').fill('12')
  await dialog.getByRole('button', { name: 'Add ready node' }).click()

  await expect(page.getByRole('heading', { name: 'Lead time' })).toBeVisible()
  const inspector = page.getByRole('complementary', { name: 'Selection inspector' })
  await expect(inspector.getByText('Native quantity')).toBeVisible()
  await expect(inspector.getByText('0–30')).toBeVisible()
  await expect(inspector.getByText('Point · 12')).toBeVisible()
  await expect(inspector.getByText('Delivery dashboard')).toBeVisible()

  await inspector.getByRole('button', { name: 'Estimate' }).click()
  await expect(page.getByRole('heading', { name: 'Set quantity estimate' })).toBeVisible()
  await page.getByRole('button', { name: 'Fermi equation' }).click()
  await page.getByRole('button', { name: /Fermi decomposition/ }).click()
  await expect(page.getByLabel('Fermi goal unit')).toHaveValue('day')
  await expect(page.getByLabel('Fermi equation')).toHaveValue('x + y')
  await expect(page.getByText(/4,000 deterministic samples/)).toBeVisible()
  await page.getByRole('button', { name: 'Assess equation' }).click()
  await expect(page.getByRole('button', { name: 'Use Fermi equation' })).toBeVisible()
  await page.getByRole('button', { name: 'Use Fermi equation' }).click()
  await page.getByRole('button', { name: 'Replace estimate' }).click()

  await expect(inspector.getByText(/Scaled Beta · \[0, 30\]/)).toBeVisible()
  await inspector.getByRole('button', { name: 'Estimate' }).click()
  await expect(page.getByText('Stored effective result')).toBeVisible()
  await expect(page.getByLabel('Fermi equation')).toHaveValue('x + y')
  await page.getByRole('button', { name: 'Close' }).click()

  await page.getByRole('button', { name: 'Add node' }).last().click()
  const factorDialog = page.locator('.node-dialog')
  await factorDialog.getByLabel('Title').fill('Flow health')
  await factorDialog.getByRole('button', { name: 'Continue' }).click()
  await factorDialog.getByRole('button', { name: 'Add ready node' }).click()

  await page.getByRole('button', { name: 'Relationship', exact: true }).click()
  const relationship = page.getByRole('form', { name: 'Add relationship' })
  await relationship.getByRole('combobox').first().selectOption('contributes')
  await page.getByLabel('Source').selectOption('B')
  await page.getByLabel('Destination').selectOption('A')
  await page.getByLabel(/Source change/).fill('0.1')
  await page.getByLabel(/Destination change/).fill('-2')
  await page.getByLabel('Mechanism').fill('Healthier flow reduces lead time.')
  await relationship.getByRole('button', { name: 'Add relationship' }).click()

  await page.getByRole('button', { name: 'Edit focused relationship B contributes A' }).click()
  await expect(page.getByText('0.1 1 → Point · -2 day')).toBeVisible()
  await page.getByRole('button', { name: 'Edit destination response estimate' }).click()
  await page.getByRole('button', { name: 'Fermi equation' }).click()
  await page.getByRole('button', { name: /Fermi decomposition/ }).click()
  await expect(page.getByLabel('Fermi goal unit')).toHaveValue('day')
  await page.getByLabel('Fermi equation').fill('x - y')
  await page.getByRole('button', { name: 'Assess equation' }).click()
  await expect(page.getByRole('button', { name: 'Use Fermi equation' })).toBeVisible()
  await page.getByRole('button', { name: 'Use Fermi equation' }).click()
  await page.getByRole('button', { name: 'Replace estimate' }).click()
  await expect(page.getByText(/Fermi · x - y/)).toBeVisible()
})
