import { expect, test } from '@playwright/test'
import { createProject } from '../support/workbench'

test('defines and derives a metric estimate in native units', async ({ page }) => {
  await createProject(page, 'Native metric quantity')
  await page.getByRole('button', { name: 'Add node' }).last().click()
  const dialog = page.locator('.node-dialog')
  await dialog.getByLabel('metric').check()
  await dialog.getByLabel('Title').fill('Lead time')
  await dialog.getByLabel('Unit').fill('days')
  await dialog.getByLabel('Aggregation').fill('p95 weekly')
  await dialog.getByLabel('Support').selectOption('bounded')
  await dialog.getByLabel('Minimum').fill('0')
  await dialog.getByLabel('Maximum').fill('30')
  await dialog.getByLabel('Operational definition').fill('Elapsed calendar days from commit to production for completed changes.')
  await dialog.getByLabel('Reference time').fill('Next 30 days')
  await dialog.getByLabel('Resolution source').fill('Delivery dashboard')
  await dialog.getByRole('button', { name: 'Add node' }).click()

  await expect(page.getByRole('heading', { name: 'Lead time' })).toBeVisible()
  const inspector = page.getByRole('complementary', { name: 'Selection inspector' })
  await expect(inspector.getByText('Native quantity')).toBeVisible()
  await expect(inspector.getByText('0–30')).toBeVisible()
  await expect(inspector.getByText('Not set')).toBeVisible()
  await expect(inspector.getByText('Delivery dashboard')).toBeVisible()

  await inspector.getByRole('button', { name: 'Estimate' }).click()
  await expect(page.getByRole('heading', { name: 'Set quantity estimate' })).toBeVisible()
  await page.getByLabel('Squiggle source').fill('truncate(gamma(4, 3) + triangular(0, 2, 5), 0, 30)')
  await expect(page.getByText(/effective samples/)).toBeVisible()
  await page.getByRole('button', { name: 'Set estimate' }).click()

  await expect(inspector.getByText(/Empirical/)).toBeVisible()
  await inspector.getByRole('button', { name: 'Estimate' }).click()
  await expect(page.getByLabel('Squiggle source')).toHaveValue('truncate(gamma(4, 3) + triangular(0, 2, 5), 0, 30)')
  await page.getByRole('button', { name: 'Close' }).click()

  await page.getByRole('button', { name: 'Add node' }).last().click()
  const factorDialog = page.locator('.node-dialog')
  await factorDialog.getByLabel('Title').fill('Flow health')
  await factorDialog.getByRole('button', { name: 'Add node' }).click()

  await page.getByRole('button', { name: 'Relationship', exact: true }).click()
  const relationship = page.getByRole('form', { name: 'Add relationship' })
  await relationship.getByRole('combobox').first().selectOption('contributes')
  await page.getByLabel('Source').selectOption('B')
  await page.getByLabel('Destination').selectOption('A')
  await page.getByLabel('Squiggle source').fill('pointMass(-2)')
  await expect(page.getByText(/effective samples/)).toBeVisible()
  await relationship.getByRole('button', { name: 'Add relationship' }).click()

  await page.getByRole('button', { name: 'Edit focused relationship B contributes A' }).click()
  await expect(page.getByText('Empirical · 2,048 samples')).toBeVisible()
  await page.getByRole('button', { name: 'Edit proportional response estimate' }).click()
  await page.getByLabel('Squiggle source').fill('normal(-2, 0.5)')
  await expect(page.getByText(/Validated/)).toBeVisible()
  await page.getByRole('button', { name: 'Replace estimate' }).click()
  await expect(page.getByText('Empirical · 2,048 samples')).toBeVisible()
})
