import { test, expect, expectCanvasPainted } from '../support/mock-api'

test('creates nodes and a relationship, then filters and inspects the model', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'desktop workflow assertion')
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Create your first project' })).toBeVisible()
  await page.getByRole('button', { name: 'Create project' }).click()
  await page.getByLabel('Project name').fill('Delivery reliability')
  await page.getByRole('button', { name: 'Create project' }).last().click()
  await expect(page.getByRole('heading', { name: 'Start with a system element' })).toBeVisible()

  await page.getByRole('button', { name: 'Add node' }).last().click()
  await page.getByLabel('Title').fill('Fast feedback')
  await page.getByLabel('Directly controllable').check()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: 'Add node' }).last().click()
  await page.getByRole('button', { name: 'Add node' }).first().click()
  await page.getByLabel('Title').fill('Learning rate')
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByRole('button', { name: 'Add node' }).last().click()

  await page.getByRole('button', { name: 'Relationship', exact: true }).click()
  await page.getByRole('form', { name: 'Add relationship' }).getByRole('combobox').first().selectOption('part_of')
  await page.getByLabel('Source').selectOption('A')
  await page.getByLabel('Destination').selectOption('B')
  await page.getByRole('button', { name: 'Add relationship' }).click()

  await expect(page.getByTestId('graph-surface')).toBeVisible()
  await page.getByRole('button', { name: /Fast feedback/ }).click()
  await expect(page.getByRole('heading', { name: 'Fast feedback' })).toBeVisible()
  await expect(page.getByText('Controllable')).toBeVisible()
  await expect(page.getByText('1 relationships')).toBeVisible()
  const selectedOutlineNode = page.getByLabel('Node outline').getByRole('button', { name: /Fast feedback/ })
  await selectedOutlineNode.focus()
  await selectedOutlineNode.press('ArrowDown')
  await expect(page.getByRole('heading', { name: 'Learning rate' })).toBeVisible()
  await page.getByRole('button', { name: 'Table view' }).click()
  const nodeTable = page.getByRole('table', { name: 'Visible graph nodes' })
  await expect(nodeTable.getByRole('button', { name: 'Learning rate' })).toHaveAttribute('aria-current', 'true')
  await expect(nodeTable.getByRole('row', { name: /B Learning rate factor/ })).toHaveClass(/selected/)
  await expectCanvasPainted(page)
  await page.screenshot({ path: 'artifacts/workbench-desktop.png', fullPage: true })

  await page.getByLabel('Search graph').fill('missing')
  await expect(page.getByText('0 nodes')).toBeVisible()
  await expect(page.getByText('0 relationships')).toBeVisible()
  await page.getByLabel('Search graph').fill('feedback')
  await expect(page.getByText('1 nodes')).toBeVisible()
})
